// src/content/commons/en/commonsShell.content.js
// English mirror of the Commons Engine shell copy. Scaffolded for future locale support;
// locale is hardcoded to 'he' in App.jsx today.

export const commonsShellContent = {
  appName: 'Commons',
  loadingInWorkspace: "Checking what's happening in ",
  nav: {
    myTasks: 'My tasks',
    board: 'All tasks',
    overview: 'Status',
    menuAriaLabel: 'Commons navigation',
    backAria: 'Back',
  },
  guard: {
    unsavedTitle: 'You have unsaved changes',
    unsavedBody: 'Save them before you leave?',
    stay: 'Stay',
    leave: 'Leave without saving',
    save: 'Save',
    discard: 'Discard changes',
  },
  snapshot: {
    heading: "What's happening today?",
    center: 'Where are we?',
    countOf: 'of',                   // "14 of 19"
    scopeAll: 'All',
    approaching: 'Time almost up',
    free: 'Free — who takes it?',
    stuck: 'Stuck — who grabs it?',
    recent: 'Lately',
    fullLog: 'Full log →',
    week: 'Recent days',
    listToggle: 'List',
    empty: 'Nothing to show here yet.',
    openDayAria: 'Open the day view',
    // actions (reuse occurrence ops) — label + separate decorative emoji (renders on its own line)
    claim: 'On me', claimE: '🙌',
    didHappen: 'It did happen', didHappenE: '🫢',
    deferTomorrow: 'To tomorrow', deferTomorrowE: '🙆',
    deferDate: 'Another day', deferDateE: '📅',
    skip: 'Not needed', skipE: '🤷',
    // open / stuck row meta + full-list words
    until: 'by',
    since: 'since ',
    yesterday: 'yesterday',
    sincePrev: 'from a previous day',
    by: 'by',
    onPerson: 'on',
    listDone: 'done',
    listOpen: 'open',
    durHours: 'hrs',
    durHour: 'an hour',
    durMins: 'min',
    // "stuck" waiting lines — picked per item. {time} = since-clock, {dur} = elapsed.
    stuckLines: [
      'waiting since {time} 👀',
      'abandoned since {time} 🥺',
      'sitting quietly for {dur} 🤫',
      'set aside since {time} 🪑',
      'missing you for {dur} 🫶',
      'forgotten since {time} 🌵',
      'anyone? already {dur} 🛎️',
      'stuck since {time} 🧊',
      'still here… {dur} 🥱',
      'patience running out… {dur} ⌛',
    ],
    // credit-line pools — picked per completion (the fun part: which one did I get?)
    creditOnTime: [
      'done, this time 🙂',
      'went smooth ✨',
      'came out well 👌',
      'closed easily 💪',
      'hit the target 🎯',
      'handled it ✅',
      'done right ✔️',
      'sorted it 🤙',
      'complete 🟢',
    ],
    creditLate: [
      'late — but saved it 🫢',
      'late but done 🙈',
      'slow… but done 🐢',
      'better late than never ⏰',
      'got there in the end 😮‍💨',
      'a bit late, big heart ❤️',
      'last-minute save 😅',
      'patience paid off 🧘',
      'well, it happened 🤷',
    ],
    closedTitle: 'You closed the whole day!',
    closedBody: 'What a team 🌈🎉',
    // living-line templates: {done},{left},{free} interpolated by the page
    lineMorning: "Morning. {left} things waiting. No rush — let's start.",
    lineMidday: '{done} already happened. {left} left — {free} free. Who takes them?',
    lineEvening: 'Almost there. {left} left — who closes them?',
    lineHardDay: 'Busy day — a few things got stuck. Worth a look?',
    lineAllDone: 'All closed. Well done 🌈',
    timeLeftMin: '{n} min left',
    noOwner: 'No owner',
    // attribution picker (resolve "it did happen" → who + when; manager assign → who)
    assign: 'On them', assignE: '🫵',
    whoTitle: 'Who did it?',
    whoAssign: 'Put it on whom?',
    whenNow: 'Now',
    whenEarlier: 'Earlier',
    nobody: 'Not sure',
    confirm: 'Record',
    cancel: 'Cancel',
    overdueTitle: 'Past time — who grabs it?',
    inProgressTitle: "What's in motion?",
    countFree: '{n} free',
    countInProgress: '{n} in motion',
    countOverdue: '{n} overdue',
    laterCount: '{n} appear later →',
    takeAllTitle: 'Take the whole thing?',
    takeAllBody: 'All sub-tasks of "{title}" become yours.',
  },
  day: {
    back: 'Back',
    toHandle: 'Still to handle',
    done: 'Done',
    lateTag: 'late',
  },
  dashboard: {
    emptyTitle: 'All calm here',
    emptyBody: 'No tasks yet. We will fill this soon.',
  },
  comingSoon: {
    title: 'Coming soon',
    body: 'Still working on it.',
  },
  picker: {
    title: 'Where are we working today?',
    subtitle: 'Pick a workspace to jump in.',
    chooseAria: 'Choose a workspace',
  },
  switcher: {
    title: 'Switch workspace',
    triggerAria: 'Switch workspace',
  },
  menu: {
    triggerAria: 'Menu',
    title: 'Menu',
    newTask: 'New task',
    newFolder: 'New folder',
    switchWorkspace: 'Switch workspace',
    members: 'Members',
    roles: 'Abilities',
    settings: 'User settings',
    backToSite: 'Back to Kfar Hirur',
    brandedBy: 'A Kfar Hirur product',
  },
  account: {
    title: 'User settings',
    intro: 'These details belong to your account — they are the same across every Kfar Hirur product.',
    nameLabel: 'Name',
    namePlaceholder: 'What should we call you?',
    emailLabel: 'Email',
    changeAvatar: 'Change photo',
    save: 'Save',
    saving: 'Saving…',
    saved: 'Saved ✓',
    signOut: 'Sign out',
    deleteAccount: 'Delete account',
    deleteTitle: 'Delete your account?',
    deleteBody: 'This is permanent: your account and all associated data will be removed from every Kfar Hirur product. This cannot be undone.',
    deleteConfirm: 'Delete permanently',
    deleting: 'Deleting…',
    cancel: 'Cancel',
    errorPrefix: 'Error:',
  },
  rolesScreen: {
    title: 'Abilities',
    subtitle: 'What people can do here — attach them to tasks and teammates.',
    add: 'New ability',
    namePlaceholder: 'Ability name (line cook, waiter…)',
    colorLabel: 'Color',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    empty: 'No abilities yet. Add the first one.',
    back: 'Back',
    cancel: 'Cancel',
    deleteTitle: 'Delete this ability?',
    deleteBody: 'It will be removed from all tasks and teammates.',
  },
  members: {
    title: 'Team',
    subtitle: 'Who is on the team, what each can do, and their permissions.',
    colMember: 'Member',
    colSkills: 'What can I do?',
    levelAdmin: 'Admin',
    levelManager: 'Manager',
    levelMember: 'Member',
    levelLabel: 'Permission',
    skillsPlaceholder: 'Choose',
    noSkills: 'No abilities defined yet',
    firstName: 'First name',
    lastName: 'Last name',
    namePlaceholder: 'Name',
    requiredField: 'Required field',
    joined: 'Joined',
    actions: 'Actions',
    edit: 'Edit',
    done: 'Done',
    save: 'Save',
    remove: 'Remove',
    removeConfirm: 'Remove this member from the workspace?',
    removeTitle: 'Remove from workspace?',
    removeBody: 'They will lose access to this workspace.',
    cancel: 'Cancel',
    cancelInviteTitle: 'Cancel this invite?',
    cancelInviteBody: 'The pending invite will be deleted.',
    lastAdmin: 'At least one admin must remain.',
    empty: 'No members yet.',
    back: 'Back',
    invite: 'Invite member',
    inviteTitle: 'Invite a new member',
    inviteEmail: 'Email',
    inviteEmailPlaceholder: 'name@example.com',
    inviteSend: 'Send invite',
    inviteLinkLabel: 'Join link',
    inviteCopy: 'Copy',
    inviteCopied: 'Copied!',
    inviteSent: 'Invite emailed.',
    inviteEmailFailed: 'Link ready to copy (email send failed).',
    pendingTitle: 'Pending invites',
    pendingStatus: 'pending',
    resend: 'Resend',
    resent: 'Sent ✓',
    cancelInvite: 'Cancel',
    close: 'Close',
  },
  join: {
    title: 'Workspace invitation',
    invitedTo: "You've been invited to",
    asLevel: 'as',
    skills: 'Abilities',
    accept: 'Accept & join',
    decline: 'Decline',
    signInFirst: 'Sign in or sign up to accept.',
    notFound: 'Invite not found or already handled.',
    pendingTitle: "You're invited",
    yourWorkspaces: 'Your workspaces',
    loading: 'One sec…',
  },
  fab: { newTaskAria: 'New task' },
  myTasks: {
    title: 'My tasks',
    filterToday: 'Today',
    filterOverdue: 'Overdue',
    filterAll: 'All',
    empty: 'Nothing assigned to you right now.',
    noArea: 'General',
    openTaskAria: 'Open task',
  },
  board: {
    rootAreaTitle: 'General tasks',
    open: 'open',
    overdue: 'overdue',
    empty: 'No areas yet. An admin can add a folder to start.',
    openAreaAria: 'Open area',
    back: 'Back',
  },
  form: {
    newTaskTitle: 'New task',
    newFolderTitle: 'New folder',
    editTaskTitle: 'Edit task',
    editFolderTitle: 'Edit folder',
    titleLabel: 'Title',
    location: 'Location',
    locationRoot: 'Top level',
    description: 'Description',
    descriptionPlaceholder: 'Details, notes, links…',
    owner: 'Who took it?',
    unassigned: 'Unassigned',
    ownerOpen: 'Open — whoever takes it',
    skill: 'Who can?',
    skillAnyone: 'Anyone',
    scheduling: 'Scheduling',
    once: 'One-off',
    repeats: 'Repeats',
    due: 'By date (deadline)',
    startDate: 'On date (start — optional)',
    orderDays: 'On which days',
    orderDaysHint: "Only from the routine's days. No selection = same as the routine.",
    dueTime: 'By time',
    showFrom: 'Appears from',
    showFromHint: 'Shows in "What\'s happening today" only from this time (optional)',
    nextMorning: 'Tomorrow morning (the work day ends at 08:00)',
    completionStyle: 'Completing the task',
    completionConfirm: 'With confirm',
    completionConfirmHint: 'Confirm sheet + optional note',
    completionQuick: 'One tap',
    completionQuickHint: 'A tick marks it done. Fast.',
    create: 'Create',
    save: 'Save',
    back: 'Back',
    delete: 'Delete',
    cancel: 'Cancel',
    deleteTitle: 'Delete?',
    deleteBody: "This can't be undone.",
    subtasksLive: 'Saved instantly',
    removeSub: 'Remove',
    removeSubTitle: 'Remove sub-task?',
    occurrenceNote: "Editing today's occurrence only — not the recurring task.",
  },
  view: {
    back: 'Back',
    edit: 'Edit',
    markDone: 'Mark done',
    reopen: 'Reopen',
    noDescription: 'No description.',
    owner: 'Who took it?',
    unassigned: 'Unassigned',
    ownerOpen: 'Open — whoever takes it',
    skill: 'Who can?',
    due: 'Due date',
    statusOpen: 'Open',
    statusDone: 'Done',
    statusMissed: 'Missed',
    subtasks: 'Sub-tasks',
    addSub: 'Add sub-task',
    addSubDetailed: 'Open task with details',
    completeAll: 'Complete all',
    confirmTitle: 'Open sub-tasks remain',
    bandToday: 'Today',
    bandPast: 'Earlier',
    bandFuture: 'Upcoming',
    bandDefs: 'Routines · settings',
    noRunToday: 'No run for today.',
    bandTodayEmpty: 'Nothing for today here.',
    noPast: 'No history yet.',
    noFuture: 'Nothing planned ahead.',
    items: 'items',
    everyDay: 'Every day',
    settingsDays: 'Days',
    addOrder: 'Add a recurring order',
    didHappen: 'It did happen',
    didHappenTitle: 'Who did it?',
    didHappenConfirm: 'Mark done',
    deferTitle: 'Defer / skip',
    deferTomorrow: 'Defer to tomorrow',
    deferDate: 'Defer to another date…',
    deferSkip: 'Not needed this time',
    late: 'late',
    hasNote: 'Has a note',
    standingTitle: 'Standing notes',
    standingHint: 'Shows on every occurrence',
    standingFromRoutine: 'From the routine',
    standingRemoveTitle: 'Remove standing note?',
    ownerChange: 'Who took it?',
    ownerSave: 'Save',
    removeMe: 'Remove me',
    cloneRoutine: 'Duplicate routine',
    editSeriesTitle: 'Edit the recurring task',
    editSeriesBody: "You're editing the recurring task. Today's run already went out — the change takes effect tomorrow.",
    editSeriesConfirm: 'OK',
    editTodayOnly: "Edit today only",
    cancelDay: "Cancel today's run",
    cancelDayTitle: "Cancel today's run?",
    cancelDayBody: "All of today's not-yet-done items will be marked cancelled.",
    // completion sheet
    completeQuestion: 'Done with',
    completeCheer: 'Nice — one more thing done together',
    completeYes: 'Yes, done',
    addNotePrompt: 'Add a note? (optional)',
    notePlaceholder: 'Leave a word for whoever comes next…',
    ownerConflictTitle: 'Complete anyway?',
    ownerConflictBody: 'took this on. If you finish it, it’s credited to you.',
    ownerConflictYes: 'Yes, all good — I’ll finish it',
    ownerConflictNo: 'No, I’ll check',
    allDoneCheer: 'All done! 🎉',
    // documentation box ("What happened here")
    docTitle: 'What happened here',
    docAdd: 'Add a note, photo or link',
    docPlaceholder: 'Add a note, photo or link…',
    docPost: 'Post',
    docPhoto: 'Photo',
    docImgCamera: 'Camera',
    docImgGallery: 'Gallery',
    docLink: 'Link',
    docFile: 'File',
    docLinkUrl: 'Link (URL)',
    docLinkName: 'Short name',
    docLinkAdd: 'Add',
    docLinkCancel: 'Cancel',
    docCompletionBadge: 'marked done',
    docDelete: 'Delete',
    docDeleteTitle: 'Delete this entry?',
    docDeleteBody: 'This cannot be undone.',
    docDeleteCancel: 'Cancel',
    docTooBig: 'File too large (max 5MB).',
    // activity log — derived, read-only; below the manual doc box
    activityTitle: 'Activity log',
    activityShowMore: 'Show all',
    activityShowLess: 'Show less',
    activityLate: 'late',
    activityTypes: {
      created: 'created',
      edited: 'edited',
      claimed: 'taken',
      unclaimed: 'released',
      reassigned: 'reassigned',
      completed: 'completed',
      reopened: 'reopened',
      missed: 'missed',
      resolved: 'marked as done',
      deferred: 'deferred',
      cancelled: 'cancelled',
    },
    activityFields: {
      title: 'title', description: 'description', due: 'due', time: 'target time',
      roles: 'skills', schedule: 'schedule', days: 'days', start: 'start date',
    },
    activityEmoji: {
      created: '✨', edited: '✏️', claimed: '🙌', unclaimed: '🤲', reassigned: '🔄',
      completed: '😎', completedLate: '😅', reopened: '🔁', missed: '🫠', resolved: '🫢',
      deferred: '🙆', cancelled: '🤷',
    },
  },
  tasks: {
    confirmMark: 'Needs confirm on complete',
    addTask: 'New task',
    addContainer: 'New folder',
    newTaskPlaceholder: 'What needs doing?',
    newContainerPlaceholder: 'Folder name',
    add: 'Add',
    cancel: 'Cancel',
    emptyTitle: 'No tasks yet',
    emptyBody: 'Add the first one below.',
    detailTitle: 'Task details',
    titleLabel: 'Title',
    description: 'Description',
    descriptionPlaceholder: 'Details, notes, links…',
    assignee: 'Owner',
    unassigned: 'Unassigned',
    dueDate: 'Due date',
    noDue: 'No date',
    save: 'Save',
    delete: 'Delete',
    addChildAria: 'Add to folder',
    toggleDoneAria: 'Mark task done',
    expandAria: 'Expand or collapse folder',
    openTaskAria: 'Open task details',
    claim: 'On me',
    claimAria: 'Take this on',
    claimNoSkill: "You don't hold the required skill",
    missed: 'Missed',
    recurrence: {
      label: 'Repeat',
      none: 'Off',
      freq: { daily: 'Daily', weekly: 'Weekly', monthly: 'Monthly' },
      everyLabel: 'Every',
      intervalLabel: 'Interval',
      pickDays: 'On which days',
      onDays: 'on ',
      dayShort: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
      units: {
        day: { one: 'day', two: '2 days', many: 'days' },
        week: { one: 'week', two: '2 weeks', many: 'weeks' },
        month: { one: 'month', two: '2 months', many: 'months' },
      },
      until: 'until',
      untilLabel: 'By time',
      nextDay: 'next day',
      partOfSeries: 'Part of a recurring task',
    },
  },
  access: {
    loading: "Checking what's happening…",
    noAccessTitle: "Oops, you don't have access here yet",
    noAccessBody: 'This space is for team members only. Ask an admin to add you.',
    backToSite: 'Back to site',
  },
};
