// src/content/commons/en/commonsShell.content.js
// English mirror of the Commons Engine shell copy. Scaffolded for future locale support;
// locale is hardcoded to 'he' in App.jsx today.

export const commonsShellContent = {
  appName: 'Commons',
  loadingInWorkspace: "Checking what's happening in ",
  nav: {
    myTasks: 'My tasks',
    board: 'All tasks',
    overview: 'Status',
    menuAriaLabel: 'Commons navigation',
  },
  snapshot: {
    open: 'Open',
    overdue: 'Overdue',
    doneToday: 'Done today',
    byArea: 'By area',
    activity: 'Recent activity',
    added: 'Added',
    done: 'Completed',
    empty: 'Nothing to show here yet.',
  },
  dashboard: {
    emptyTitle: 'All calm here',
    emptyBody: 'No tasks yet. We will fill this soon.',
  },
  comingSoon: {
    title: 'Coming soon',
    body: 'Still working on it.',
  },
  picker: {
    title: 'Where are we working today?',
    subtitle: 'Pick a workspace to jump in.',
    chooseAria: 'Choose a workspace',
  },
  switcher: {
    title: 'Switch workspace',
    triggerAria: 'Switch workspace',
  },
  menu: {
    triggerAria: 'Menu',
    title: 'Menu',
    newTask: 'New task',
    newFolder: 'New folder',
    switchWorkspace: 'Switch workspace',
    members: 'Members',
    roles: 'Abilities',
    backToSite: 'Back to Kfar Hirur',
  },
  rolesScreen: {
    title: 'Abilities',
    subtitle: 'What people can do here — attach them to tasks and teammates.',
    add: 'New ability',
    namePlaceholder: 'Ability name (line cook, waiter…)',
    colorLabel: 'Color',
    save: 'Save',
    rename: 'Rename',
    delete: 'Delete',
    empty: 'No abilities yet. Add the first one.',
    back: 'Back',
  },
  members: {
    title: 'Team',
    subtitle: 'Who is on the team, what each can do, and their permissions.',
    colMember: 'Member',
    colSkills: 'What can I do?',
    levelAdmin: 'Admin',
    levelManager: 'Manager',
    levelMember: 'Member',
    levelLabel: 'Permission',
    skillsPlaceholder: 'Choose',
    noSkills: 'No abilities defined yet',
    firstName: 'First name',
    lastName: 'Last name',
    namePlaceholder: 'Name',
    joined: 'Joined',
    actions: 'Actions',
    edit: 'Edit',
    done: 'Done',
    remove: 'Remove',
    removeConfirm: 'Remove this member from the workspace?',
    lastAdmin: 'At least one admin must remain.',
    empty: 'No members yet.',
    back: 'Back',
  },
  fab: { newTaskAria: 'New task' },
  myTasks: {
    title: 'My tasks',
    filterToday: 'Today',
    filterOverdue: 'Overdue',
    filterAll: 'All',
    empty: 'Nothing assigned to you right now.',
    noArea: 'General',
    openTaskAria: 'Open task',
  },
  board: {
    rootAreaTitle: 'General tasks',
    open: 'open',
    overdue: 'overdue',
    empty: 'No areas yet. An admin can add a folder to start.',
    openAreaAria: 'Open area',
    back: 'Back',
  },
  form: {
    newTaskTitle: 'New task',
    newFolderTitle: 'New folder',
    editTaskTitle: 'Edit task',
    editFolderTitle: 'Edit folder',
    titleLabel: 'Title',
    location: 'Location',
    locationRoot: 'Top level',
    description: 'Description',
    descriptionPlaceholder: 'Details, notes, links…',
    owner: 'Owner',
    unassigned: 'Unassigned',
    skill: 'Who can?',
    skillAnyone: 'Anyone',
    scheduling: 'Scheduling',
    once: 'One-off',
    repeats: 'Repeats',
    due: 'Due date',
    create: 'Create',
    save: 'Save',
    back: 'Back',
    delete: 'Delete',
  },
  view: {
    back: 'Back',
    edit: 'Edit',
    markDone: 'Mark done',
    reopen: 'Reopen',
    noDescription: 'No description.',
    owner: 'Owner',
    unassigned: 'Unassigned',
    skill: 'Who can?',
    due: 'Due date',
    statusOpen: 'Open',
    statusDone: 'Done',
    statusMissed: 'Missed',
    subtasks: 'Sub-tasks',
    addSub: 'Add sub-task',
    addSubDetailed: 'Open task with details',
    completeAll: 'Complete all',
    confirmTitle: 'Open sub-tasks remain',
    stillOpen: 'Still open',
  },
  tasks: {
    addTask: 'New task',
    addContainer: 'New folder',
    newTaskPlaceholder: 'What needs doing?',
    newContainerPlaceholder: 'Folder name',
    add: 'Add',
    cancel: 'Cancel',
    emptyTitle: 'No tasks yet',
    emptyBody: 'Add the first one below.',
    detailTitle: 'Task details',
    titleLabel: 'Title',
    description: 'Description',
    descriptionPlaceholder: 'Details, notes, links…',
    assignee: 'Owner',
    unassigned: 'Unassigned',
    dueDate: 'Due date',
    noDue: 'No date',
    save: 'Save',
    delete: 'Delete',
    addChildAria: 'Add to folder',
    toggleDoneAria: 'Mark task done',
    expandAria: 'Expand or collapse folder',
    openTaskAria: 'Open task details',
    claim: 'On me',
    claimAria: 'Take this on',
    claimNoSkill: "You don't hold the required skill",
    missed: 'Missed',
    recurrence: {
      label: 'Repeat',
      none: 'No repeat',
      freq: { daily: 'Daily', weekly: 'Weekly', monthly: 'Monthly' },
      everyLabel: 'Every',
      intervalLabel: 'Interval',
      pickDays: 'On which days',
      onDays: 'on ',
      dayShort: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
      units: {
        day: { one: 'day', two: '2 days', many: 'days' },
        week: { one: 'week', two: '2 weeks', many: 'weeks' },
        month: { one: 'month', two: '2 months', many: 'months' },
      },
      until: 'until',
      untilLabel: 'By time',
      partOfSeries: 'Part of a recurring task',
    },
  },
  access: {
    loading: "Checking what's happening…",
    noAccessTitle: "Oops, you don't have access here yet",
    noAccessBody: 'This space is for team members only. Ask an admin to add you.',
    backToSite: 'Back to site',
  },
};
