// src/content/commons/he/commonsShell.content.js
// Hebrew UI copy for the Commons Engine shell (Increment 1).
// Voice: playful, warm, light — never corporate (see docs/voice.md). Strings are placeholder-quality;
// a dedicated copy pass comes later (display name still TBD).

export const commonsShellContent = {
  appName: 'מרחב העבודה',
  loadingInWorkspace: 'בודק מה קורה ב',
  nav: {
    myTasks: 'המשימות שלי',
    board: 'כל הלוח',
    overview: 'תמונת מצב',
    menuAriaLabel: 'ניווט מרחב העבודה',
    backAria: 'חזרה',
  },
  guard: {
    unsavedTitle: 'לצאת בלי לשמור?',
    unsavedBody: 'יש שינויים שעוד לא נשמרו. אם תצאו עכשיו הם יימחקו.',
    stay: 'הישארו',
    leave: 'צאו בלי לשמור',
  },
  snapshot: {
    open: 'פתוחות',
    overdue: 'באיחור',
    doneToday: 'הושלמו היום',
    byArea: 'לפי מרחב',
    activity: 'פעילות אחרונה',
    added: 'נוסף',
    done: 'הושלם',
    empty: 'עוד אין מה להציג כאן.',
  },
  dashboard: {
    emptyTitle: 'הכל רגוע פה',
    emptyBody: 'עוד אין משימות. תכף נמלא את זה.',
  },
  comingSoon: {
    title: 'בקרוב כאן',
    body: 'עוד עובדים על זה.',
  },
  picker: {
    title: 'איפה עובדים היום?',
    subtitle: 'בחרו מרחב עבודה כדי להיכנס.',
    chooseAria: 'בחירת מרחב עבודה',
  },
  switcher: {
    title: 'מעבר בין מרחבים',
    triggerAria: 'החלפת מרחב עבודה',
  },
  menu: {
    triggerAria: 'תפריט',
    title: 'תפריט',
    newTask: 'משימה חדשה',
    newFolder: 'תיקייה חדשה',
    switchWorkspace: 'החלפת מרחב עבודה',
    members: 'ניהול חברים',
    roles: 'ניהול יכולות',
    settings: 'הגדרות משתמש',
    backToSite: 'חזרה לכפר הירעור',
    brandedBy: 'מבית כפר הירעור',
  },
  account: {
    title: 'הגדרות משתמש',
    intro: 'הפרטים האלה שייכים לחשבון שלך — והם זהים בכל המוצרים של כפר הירעור.',
    nameLabel: 'שם',
    namePlaceholder: 'איך קוראים לך?',
    emailLabel: 'אימייל',
    changeAvatar: 'שינוי תמונה',
    save: 'שמירה',
    saving: 'שומר…',
    saved: 'נשמר ✓',
    signOut: 'התנתקות',
    deleteAccount: 'מחיקת חשבון',
    deleteTitle: 'למחוק את החשבון?',
    deleteBody: 'הפעולה לצמיתות: החשבון שלך וכל המידע המשויך אליו יימחקו מכל המוצרים של כפר הירעור. אי אפשר לבטל.',
    deleteConfirm: 'מחיקה לצמיתות',
    deleting: 'מוחק…',
    cancel: 'ביטול',
    errorPrefix: 'שגיאה:',
  },
  rolesScreen: {
    title: 'יכולות',
    subtitle: 'מה אפשר לדעת לעשות פה — משייכים למשימות ולחברי הצוות.',
    add: 'יכולת חדשה',
    namePlaceholder: 'שם היכולת (טבח פס, מלצר…)',
    colorLabel: 'צבע',
    save: 'שמירה',
    edit: 'עריכה',
    delete: 'מחיקה',
    empty: 'עוד אין יכולות. הוסיפו את הראשונה.',
    back: 'חזרה',
    cancel: 'ביטול',
    deleteTitle: 'למחוק את היכולת?',
    deleteBody: 'היכולת תוסר מכל המשימות ומחברי הצוות.',
  },
  members: {
    title: 'חברי הצוות',
    subtitle: 'מי בצוות, מה כל אחד יודע, ומה ההרשאות.',
    colMember: 'חבר/ה',
    colSkills: 'מה אני יודע?',
    levelAdmin: 'אדמין',
    levelManager: 'מנהל/ת',
    levelMember: 'משתמש',
    levelLabel: 'הרשאה',
    skillsPlaceholder: 'בחר/י',
    noSkills: 'עוד אין יכולות להגדיר',
    firstName: 'שם פרטי',
    lastName: 'שם משפחה',
    namePlaceholder: 'שם',
    joined: 'הצטרף/ה',
    actions: 'פעולות',
    edit: 'עריכה',
    done: 'סיום',
    save: 'שמירה',
    remove: 'הסרה',
    removeConfirm: 'להסיר את החבר/ה מהמרחב?',
    removeTitle: 'להסיר מהמרחב?',
    removeBody: 'החבר/ה תאבד גישה למרחב העבודה.',
    cancel: 'ביטול',
    cancelInviteTitle: 'לבטל את ההזמנה?',
    cancelInviteBody: 'ההזמנה הממתינה תימחק.',
    lastAdmin: 'חייב להישאר לפחות אדמין אחד.',
    empty: 'אין עדיין חברים.',
    back: 'חזרה',
    invite: 'הזמנת חבר',
    inviteTitle: 'הזמנת חבר חדש',
    inviteEmail: 'אימייל',
    inviteEmailPlaceholder: 'name@example.com',
    inviteSend: 'שליחת הזמנה',
    inviteLinkLabel: 'לינק הצטרפות',
    inviteCopy: 'העתקה',
    inviteCopied: 'הועתק!',
    inviteSent: 'ההזמנה נשלחה במייל.',
    inviteEmailFailed: 'הלינק מוכן להעתקה (שליחת המייל לא הצליחה).',
    pendingTitle: 'הזמנות ממתינות',
    pendingStatus: 'ממתינה',
    resend: 'שליחה מחדש',
    resent: 'נשלח ✓',
    cancelInvite: 'ביטול',
    close: 'סגירה',
  },
  join: {
    title: 'הזמנה למרחב עבודה',
    invitedTo: 'הוזמנת להצטרף אל',
    asLevel: 'בתור',
    skills: 'יכולות',
    accept: 'אישור והצטרפות',
    decline: 'דחייה',
    signInFirst: 'התחברו או הירשמו כדי לאשר את ההצטרפות.',
    notFound: 'ההזמנה לא נמצאה או כבר טופלה.',
    pendingTitle: 'הוזמנת למרחב',
    yourWorkspaces: 'המרחבים שלך',
    loading: 'רגע…',
  },
  fab: { newTaskAria: 'משימה חדשה' },
  myTasks: {
    title: 'המשימות שלי',
    filterToday: 'היום',
    filterOverdue: 'באיחור',
    filterAll: 'הכל',
    empty: 'אין משימות שמשויכות אליך כרגע.',
    noArea: 'כללי',
    openTaskAria: 'פתיחת המשימה',
  },
  board: {
    rootAreaTitle: 'משימות כלליות',
    open: 'פתוחות',
    overdue: 'באיחור',
    empty: 'עוד אין מרחבים. אדמין יכול להוסיף תיקייה כדי להתחיל.',
    openAreaAria: 'פתיחת מרחב',
    back: 'חזרה',
  },
  form: {
    newTaskTitle: 'משימה חדשה',
    newFolderTitle: 'תיקייה חדשה',
    editTaskTitle: 'עריכת משימה',
    editFolderTitle: 'עריכת תיקייה',
    titleLabel: 'כותרת',
    location: 'מיקום',
    locationRoot: 'רמה ראשית',
    description: 'תיאור',
    descriptionPlaceholder: 'פרטים, הערות, קישורים…',
    owner: 'אחראי/ת',
    unassigned: 'לא משויך',
    skill: 'מי יכול?',
    skillAnyone: 'כל עובד',
    scheduling: 'תזמון',
    once: 'חד-פעמי',
    repeats: 'חוזר',
    due: 'תאריך יעד',
    create: 'יצירה',
    save: 'שמירה',
    back: 'חזרה',
    delete: 'מחיקה',
    cancel: 'ביטול',
    deleteTitle: 'למחוק?',
    deleteBody: 'אי אפשר לבטל את הפעולה.',
  },
  view: {
    back: 'חזרה',
    edit: 'עריכה',
    markDone: 'סמן כבוצע',
    reopen: 'החזר לפתוח',
    noDescription: 'אין תיאור.',
    owner: 'אחראי/ת',
    unassigned: 'לא משויך',
    skill: 'מי יכול?',
    due: 'תאריך יעד',
    statusOpen: 'פתוחה',
    statusDone: 'בוצעה',
    statusMissed: 'הוחמצה',
    subtasks: 'תת-משימות',
    addSub: 'הוספת תת-משימה',
    addSubDetailed: 'פתיחת משימה עם פרטים',
    completeAll: 'סמן הכול כבוצע',
    confirmTitle: 'יש תת-משימות פתוחות',
    stillOpen: 'פתוחות עדיין',
  },
  tasks: {
    addTask: 'משימה חדשה',
    addContainer: 'תיקייה חדשה',
    newTaskPlaceholder: 'מה צריך לעשות?',
    newContainerPlaceholder: 'שם התיקייה',
    add: 'הוספה',
    cancel: 'ביטול',
    emptyTitle: 'אין עדיין משימות',
    emptyBody: 'הוסיפו את הראשונה למטה.',
    detailTitle: 'פרטי משימה',
    titleLabel: 'כותרת',
    description: 'תיאור',
    descriptionPlaceholder: 'פרטים, הערות, קישורים…',
    assignee: 'אחראי/ת',
    unassigned: 'לא משויך',
    dueDate: 'תאריך יעד',
    noDue: 'ללא תאריך',
    save: 'שמירה',
    delete: 'מחיקה',
    addChildAria: 'הוספה לתיקייה',
    toggleDoneAria: 'סימון שהמשימה בוצעה',
    expandAria: 'פתיחה או סגירה של התיקייה',
    openTaskAria: 'פתיחת פרטי המשימה',
    claim: 'עלי',
    claimAria: 'לקחת על עצמי',
    claimNoSkill: 'אין לך את הכישור הנדרש',
    missed: 'הוחמצה',
    recurrence: {
      label: 'חזרה',
      none: 'בלי חזרה',
      freq: { daily: 'יומי', weekly: 'שבועי', monthly: 'חודשי' },
      everyLabel: 'כל',
      intervalLabel: 'כל כמה',
      pickDays: 'באילו ימים',
      onDays: 'ב',
      dayShort: ['א׳', 'ב׳', 'ג׳', 'ד׳', 'ה׳', 'ו׳', 'ש׳'],
      units: {
        day: { one: 'יום', two: 'יומיים', many: 'ימים' },
        week: { one: 'שבוע', two: 'שבועיים', many: 'שבועות' },
        month: { one: 'חודש', two: 'חודשיים', many: 'חודשים' },
      },
      until: 'עד',
      untilLabel: 'עד שעה',
      partOfSeries: 'מתוך משימה חוזרת',
    },
  },
  access: {
    loading: 'בודק מה קורה…',
    noAccessTitle: 'אופס, אין לך גישה לפה עדיין',
    noAccessBody: 'המרחב הזה פתוח רק לחברי הצוות. דברו עם מנהל כדי שיוסיפו אותך.',
    backToSite: 'חזרה לאתר',
  },
};
