// src/content/commons/he/commonsShell.content.js
// Hebrew UI copy for the Commons Engine shell (Increment 1).
// Voice: playful, warm, light — never corporate (see docs/voice.md). Strings are placeholder-quality;
// a dedicated copy pass comes later (display name still TBD).

export const commonsShellContent = {
  appName: 'מרחב העבודה',
  loadingInWorkspace: 'בודק מה קורה ב',
  nav: {
    myTasks: 'המשימות שלי',
    board: 'כל הלוח',
    overview: 'תמונת מצב',
    menuAriaLabel: 'ניווט מרחב העבודה',
    backAria: 'חזרה',
  },
  guard: {
    unsavedTitle: 'יש שינויים שלא נשמרו',
    unsavedBody: 'לשמור אותם לפני שיוצאים?',
    stay: 'הישארו',
    leave: 'צאו בלי לשמור',
    save: 'שמירה',
    discard: 'בטלו שינויים',
  },
  snapshot: {
    heading: 'מה קורה היום?',
    center: 'מה מצבנו?',
    countOf: 'מתוך',                 // "14 מתוך 19"
    scopeAll: 'הכל',
    approaching: 'תכף נגמר הזמן',
    free: 'פנוי — מי לוקח?',
    stuck: 'נתקע קצת — מי תופס?',
    recent: 'לאחרונה',
    fullLog: 'כל היומן ←',
    week: 'השבוע',
    listToggle: 'רשימה',
    empty: 'עוד אין מה להציג כאן.',
    // actions (reuse occurrence ops)
    claim: 'עליי 🙌',
    didHappen: 'זה כן קרה 🫢',
    deferTomorrow: 'דחה למחר 🙆',
    deferDate: 'תאריך אחר 📅',
    skip: 'לא צריך 🤷',
    // credit-line flavour (emoji decorative; meaning in the words)
    creditOnTime: 'בזמן, אלוף 😇',
    creditSmooth: 'חלק כרגיל 😎',
    creditLate: 'באיחור — אבל הציל/ה 🫢',
    creditClaim: 'יוזמה 🙌',
    closedTitle: 'סגרתם את כל היום!',
    closedBody: 'איזה צוות 🌈🎉',
    // living-line templates: {done},{left},{free} interpolated by the page
    lineMorning: 'בוקר. {left} דברים מחכים. אין לחץ — נתחיל.',
    lineMidday: '{done} כבר קרו. נשארו {left} — {free} פנויים. מי לוקח?',
    lineEvening: 'כמעט. נשארו {left} — מי סוגר?',
    lineHardDay: 'יום עמוס — כמה דברים נתקעו. שווה מבט?',
    lineAllDone: 'הכל סגור. כל הכבוד 🌈',
    timeLeftMin: 'עוד {n} דק׳',
    noOwner: 'אין אחראי',
  },
  dashboard: {
    emptyTitle: 'הכל רגוע פה',
    emptyBody: 'עוד אין משימות. תכף נמלא את זה.',
  },
  comingSoon: {
    title: 'בקרוב כאן',
    body: 'עוד עובדים על זה.',
  },
  picker: {
    title: 'איפה עובדים היום?',
    subtitle: 'בחרו מרחב עבודה כדי להיכנס.',
    chooseAria: 'בחירת מרחב עבודה',
  },
  switcher: {
    title: 'מעבר בין מרחבים',
    triggerAria: 'החלפת מרחב עבודה',
  },
  menu: {
    triggerAria: 'תפריט',
    title: 'תפריט',
    newTask: 'משימה חדשה',
    newFolder: 'תיקייה חדשה',
    switchWorkspace: 'החלפת מרחב עבודה',
    members: 'ניהול חברים',
    roles: 'ניהול יכולות',
    settings: 'הגדרות משתמש',
    backToSite: 'חזרה לכפר הירעור',
    brandedBy: 'מבית כפר הירעור',
  },
  account: {
    title: 'הגדרות משתמש',
    intro: 'הפרטים האלה שייכים לחשבון שלך — והם זהים בכל המוצרים של כפר הירעור.',
    nameLabel: 'שם',
    namePlaceholder: 'איך קוראים לך?',
    emailLabel: 'אימייל',
    changeAvatar: 'שינוי תמונה',
    save: 'שמירה',
    saving: 'שומר…',
    saved: 'נשמר ✓',
    signOut: 'התנתקות',
    deleteAccount: 'מחיקת חשבון',
    deleteTitle: 'למחוק את החשבון?',
    deleteBody: 'הפעולה לצמיתות: החשבון שלך וכל המידע המשויך אליו יימחקו מכל המוצרים של כפר הירעור. אי אפשר לבטל.',
    deleteConfirm: 'מחיקה לצמיתות',
    deleting: 'מוחק…',
    cancel: 'ביטול',
    errorPrefix: 'שגיאה:',
  },
  rolesScreen: {
    title: 'יכולות',
    subtitle: 'מה אפשר לדעת לעשות פה — משייכים למשימות ולחברי הצוות.',
    add: 'יכולת חדשה',
    namePlaceholder: 'שם היכולת (טבח פס, מלצר…)',
    colorLabel: 'צבע',
    save: 'שמירה',
    edit: 'עריכה',
    delete: 'מחיקה',
    empty: 'עוד אין יכולות. הוסיפו את הראשונה.',
    back: 'חזרה',
    cancel: 'ביטול',
    deleteTitle: 'למחוק את היכולת?',
    deleteBody: 'היכולת תוסר מכל המשימות ומחברי הצוות.',
  },
  members: {
    title: 'חברי הצוות',
    subtitle: 'מי בצוות, מה כל אחד יודע, ומה ההרשאות.',
    colMember: 'חבר/ה',
    colSkills: 'מה אני יודע?',
    levelAdmin: 'אדמין',
    levelManager: 'מנהל/ת',
    levelMember: 'משתמש',
    levelLabel: 'הרשאה',
    skillsPlaceholder: 'בחר/י',
    noSkills: 'עוד אין יכולות להגדיר',
    firstName: 'שם פרטי',
    lastName: 'שם משפחה',
    namePlaceholder: 'שם',
    requiredField: 'שדה חובה',
    joined: 'הצטרף/ה',
    actions: 'פעולות',
    edit: 'עריכה',
    done: 'סיום',
    save: 'שמירה',
    remove: 'הסרה',
    removeConfirm: 'להסיר את החבר/ה מהמרחב?',
    removeTitle: 'להסיר מהמרחב?',
    removeBody: 'החבר/ה תאבד גישה למרחב העבודה.',
    cancel: 'ביטול',
    cancelInviteTitle: 'לבטל את ההזמנה?',
    cancelInviteBody: 'ההזמנה הממתינה תימחק.',
    lastAdmin: 'חייב להישאר לפחות אדמין אחד.',
    empty: 'אין עדיין חברים.',
    back: 'חזרה',
    invite: 'הזמנת חבר',
    inviteTitle: 'הזמנת חבר חדש',
    inviteEmail: 'אימייל',
    inviteEmailPlaceholder: 'name@example.com',
    inviteSend: 'שליחת הזמנה',
    inviteLinkLabel: 'לינק הצטרפות',
    inviteCopy: 'העתקה',
    inviteCopied: 'הועתק!',
    inviteSent: 'ההזמנה נשלחה במייל.',
    inviteEmailFailed: 'הלינק מוכן להעתקה (שליחת המייל לא הצליחה).',
    pendingTitle: 'הזמנות ממתינות',
    pendingStatus: 'ממתינה',
    resend: 'שליחה מחדש',
    resent: 'נשלח ✓',
    cancelInvite: 'ביטול',
    close: 'סגירה',
  },
  join: {
    title: 'הזמנה למרחב עבודה',
    invitedTo: 'הוזמנת להצטרף אל',
    asLevel: 'בתור',
    skills: 'יכולות',
    accept: 'אישור והצטרפות',
    decline: 'דחייה',
    signInFirst: 'התחברו או הירשמו כדי לאשר את ההצטרפות.',
    notFound: 'ההזמנה לא נמצאה או כבר טופלה.',
    pendingTitle: 'הוזמנת למרחב',
    yourWorkspaces: 'המרחבים שלך',
    loading: 'רגע…',
  },
  fab: { newTaskAria: 'משימה חדשה' },
  myTasks: {
    title: 'המשימות שלי',
    filterToday: 'היום',
    filterOverdue: 'באיחור',
    filterAll: 'הכל',
    empty: 'אין משימות שמשויכות אליך כרגע.',
    noArea: 'כללי',
    openTaskAria: 'פתיחת המשימה',
  },
  board: {
    rootAreaTitle: 'משימות כלליות',
    open: 'פתוחות',
    overdue: 'באיחור',
    empty: 'עוד אין מרחבים. אדמין יכול להוסיף תיקייה כדי להתחיל.',
    openAreaAria: 'פתיחת מרחב',
    back: 'חזרה',
  },
  form: {
    newTaskTitle: 'משימה חדשה',
    newFolderTitle: 'תיקייה חדשה',
    editTaskTitle: 'עריכת משימה',
    editFolderTitle: 'עריכת תיקייה',
    titleLabel: 'כותרת',
    location: 'מיקום',
    locationRoot: 'רמה ראשית',
    description: 'תיאור',
    descriptionPlaceholder: 'פרטים, הערות, קישורים…',
    owner: 'מי לקח?',
    unassigned: 'לא משויך',
    skill: 'מי יכול?',
    skillAnyone: 'כל עובד',
    scheduling: 'תזמון',
    once: 'חד-פעמי',
    repeats: 'חוזר',
    due: 'עד תאריך (דדליין)',
    startDate: 'בתאריך (התחלה — לא חובה)',
    orderDays: 'באילו ימים',
    orderDaysHint: 'אפשר רק מתוך הימים של המשימה הקבועה. בלי בחירה = כמו הקבועה.',
    dueTime: 'עד שעה',
    nextMorning: 'מחר בבוקר (יום העבודה מסתיים ב־08:00)',
    completionStyle: 'סיום המשימה',
    completionConfirm: 'עם אישור',
    completionConfirmHint: 'חלון אישור + אפשרות הערה',
    completionQuick: 'בקליק',
    completionQuickHint: 'טיק מסמן שבוצע. מהיר.',
    create: 'יצירה',
    save: 'שמירה',
    back: 'חזרה',
    delete: 'מחיקה',
    cancel: 'ביטול',
    deleteTitle: 'למחוק?',
    deleteBody: 'אי אפשר לבטל את הפעולה.',
    subtasksLive: 'נשמר מיד',
    removeSub: 'הסרה',
    removeSubTitle: 'להסיר תת-משימה?',
    occurrenceNote: 'עריכת המופע של היום בלבד — לא של המשימה הקבועה.',
  },
  view: {
    back: 'חזרה',
    edit: 'עריכה',
    markDone: 'סמן כבוצע',
    reopen: 'החזר לפתוח',
    noDescription: 'אין תיאור.',
    owner: 'מי לקח?',
    unassigned: 'לא משויך',
    skill: 'מי יכול?',
    due: 'תאריך יעד',
    statusOpen: 'פתוחה',
    statusDone: 'בוצעה',
    statusMissed: 'הוחמצה',
    subtasks: 'תת-משימות',
    addSub: 'הוספת תת-משימה',
    addSubDetailed: 'פתיחת משימה עם פרטים',
    completeAll: 'סמן הכול כבוצע',
    confirmTitle: 'יש תת-משימות פתוחות',
    // routine hub (recurring task = routine; bands of runs + the definition list)
    bandToday: 'מה היום',
    bandPast: 'מה היה',
    bandFuture: 'מה יהיה',
    bandDefs: 'משימות קבועות · הגדרות',
    noRunToday: 'אין ריצה להיום.',
    bandTodayEmpty: 'אין משימות להיום כאן.',
    noPast: 'עדיין אין היסטוריה.',
    noFuture: 'אין מה שמתוכנן קדימה.',
    items: 'פריטים',
    everyDay: 'כל יום',
    addOrder: 'הוספת הזמנה קבועה',
    // occurrence actions on a run item
    didHappen: 'זה כן קרה',
    didHappenTitle: 'מי ביצע את זה?',
    didHappenConfirm: 'סימון כבוצע',
    deferTitle: 'דחה / דלג',
    deferTomorrow: 'דחה למחר',
    deferDate: 'דחה לתאריך אחר…',
    deferSkip: 'לא צריך הפעם',
    late: 'באיחור',
    hasNote: 'יש הערה',
    ownerChange: 'מי לקח?',
    ownerSave: 'שמירה',
    removeMe: 'הסר אותי',
    cloneRoutine: 'שכפול המשימה הקבועה',
    editSeriesTitle: 'עריכת משימה קבועה',
    editSeriesBody: 'עורכים את המשימה הקבועה. הריצה של היום כבר יצאה — השינוי יתפוס ממחר.',
    editSeriesConfirm: 'אישור',
    editTodayOnly: 'ערוך רק את היום',
    cancelDay: 'בטל את היום',
    cancelDayTitle: 'לבטל את הריצה של היום?',
    cancelDayBody: 'כל הפריטים שטרם בוצעו היום יסומנו כמבוטלים.',
    // completion sheet
    completeQuestion: 'סיימת את',
    completeCheer: 'כל הכבוד — עוד דבר שנעשה ביחד',
    completeYes: 'כן, סיימתי',
    addNotePrompt: 'רוצה להוסיף הערה? (לא חובה)',
    notePlaceholder: 'משאיר/ה מילה לבאים אחריך…',
    ownerConflictTitle: 'להשלים בכל זאת?',
    ownerConflictBody: 'לקח/ה את זה על עצמו/ה. אם תסיים/י — זה יירשם על שמך.',
    ownerConflictYes: 'כן, הכל טוב — אני מסיים/ת',
    ownerConflictNo: 'לא, אבדוק',
    allDoneCheer: 'סיימתם הכל! 🎉',
    // documentation box ("מה קרה כאן")
    docTitle: 'מה קרה כאן',
    docAdd: 'הוסף הערה, תמונה או קישור',
    docPlaceholder: 'הוסף פתק, תמונה או קישור…',
    docPost: 'פרסם',
    docPhoto: 'תמונה',
    docLink: 'קישור',
    docFile: 'קובץ',
    docLinkPrompt: 'הדבק קישור (URL):',
    docCompletionBadge: 'סומן כבוצע',
    docDelete: 'מחק',
    docDeleteTitle: 'למחוק את הרשומה?',
    docDeleteBody: 'אי אפשר לבטל את הפעולה.',
    docDeleteCancel: 'ביטול',
    docTooBig: 'הקובץ גדול מדי (עד 5MB).',
  },
  tasks: {
    confirmMark: 'דורש אישור בסיום',
    addTask: 'משימה חדשה',
    addContainer: 'תיקייה חדשה',
    newTaskPlaceholder: 'מה צריך לעשות?',
    newContainerPlaceholder: 'שם התיקייה',
    add: 'הוספה',
    cancel: 'ביטול',
    emptyTitle: 'אין עדיין משימות',
    emptyBody: 'הוסיפו את הראשונה למטה.',
    detailTitle: 'פרטי משימה',
    titleLabel: 'כותרת',
    description: 'תיאור',
    descriptionPlaceholder: 'פרטים, הערות, קישורים…',
    assignee: 'אחראי/ת',
    unassigned: 'לא משויך',
    dueDate: 'תאריך יעד',
    noDue: 'ללא תאריך',
    save: 'שמירה',
    delete: 'מחיקה',
    addChildAria: 'הוספה לתיקייה',
    toggleDoneAria: 'סימון שהמשימה בוצעה',
    expandAria: 'פתיחה או סגירה של התיקייה',
    openTaskAria: 'פתיחת פרטי המשימה',
    claim: 'עלי',
    claimAria: 'לקחת על עצמי',
    claimNoSkill: 'אין לך את הכישור הנדרש',
    missed: 'הוחמצה',
    recurrence: {
      label: 'חזרה',
      none: 'בלי',
      freq: { daily: 'יומי', weekly: 'שבועי', monthly: 'חודשי' },
      everyLabel: 'כל',
      intervalLabel: 'כל כמה',
      pickDays: 'באילו ימים',
      onDays: 'ב',
      dayShort: ['א׳', 'ב׳', 'ג׳', 'ד׳', 'ה׳', 'ו׳', 'ש׳'],
      units: {
        day: { one: 'יום', two: 'יומיים', many: 'ימים' },
        week: { one: 'שבוע', two: 'שבועיים', many: 'שבועות' },
        month: { one: 'חודש', two: 'חודשיים', many: 'חודשים' },
      },
      until: 'עד',
      untilLabel: 'עד שעה',
      nextDay: 'למחרת',
      partOfSeries: 'מתוך משימה חוזרת',
    },
  },
  access: {
    loading: 'בודק מה קורה…',
    noAccessTitle: 'אופס, אין לך גישה לפה עדיין',
    noAccessBody: 'המרחב הזה פתוח רק לחברי הצוות. דברו עם מנהל כדי שיוסיפו אותך.',
    backToSite: 'חזרה לאתר',
  },
};
