// src/content/commons/he/commonsShell.content.js
// Hebrew UI copy for the Commons Engine shell (Increment 1).
// Voice: playful, warm, light — never corporate (see docs/voice.md). Strings are placeholder-quality;
// a dedicated copy pass comes later (display name still TBD).

export const commonsShellContent = {
  appName: 'מרחב העבודה',
  loadingInWorkspace: 'בודק מה קורה ב',
  nav: {
    myTasks: 'המשימות שלי',
    board: 'כל הלוח',
    overview: 'תמונת מצב',
    menuAriaLabel: 'ניווט מרחב העבודה',
  },
  snapshot: {
    open: 'פתוחות',
    overdue: 'באיחור',
    doneToday: 'הושלמו היום',
    byArea: 'לפי מרחב',
    activity: 'פעילות אחרונה',
    added: 'נוסף',
    done: 'הושלם',
    empty: 'עוד אין מה להציג כאן.',
  },
  dashboard: {
    emptyTitle: 'הכל רגוע פה',
    emptyBody: 'עוד אין משימות. תכף נמלא את זה.',
  },
  comingSoon: {
    title: 'בקרוב כאן',
    body: 'עוד עובדים על זה.',
  },
  picker: {
    title: 'איפה עובדים היום?',
    subtitle: 'בחרו מרחב עבודה כדי להיכנס.',
    chooseAria: 'בחירת מרחב עבודה',
  },
  switcher: {
    title: 'מעבר בין מרחבים',
    triggerAria: 'החלפת מרחב עבודה',
  },
  menu: {
    triggerAria: 'תפריט',
    title: 'תפריט',
    newTask: 'משימה חדשה',
    newFolder: 'תיקייה חדשה',
    switchWorkspace: 'החלפת מרחב עבודה',
    members: 'ניהול משתמשים',
    roles: 'ניהול כישורים',
    backToSite: 'חזרה לכפר הירעור',
  },
  rolesScreen: {
    title: 'כישורים',
    subtitle: 'הכישורים שאפשר לשייך למשימות ולחברי הצוות.',
    add: 'כישור חדש',
    namePlaceholder: 'שם הכישור (טבח פס, מלצר…)',
    colorLabel: 'צבע',
    save: 'שמירה',
    rename: 'שינוי שם',
    delete: 'מחיקה',
    empty: 'עוד אין כישורים. הוסיפו את הראשון.',
    back: 'חזרה',
  },
  fab: { newTaskAria: 'משימה חדשה' },
  myTasks: {
    title: 'המשימות שלי',
    filterToday: 'היום',
    filterOverdue: 'באיחור',
    filterAll: 'הכל',
    empty: 'אין משימות שמשויכות אליך כרגע.',
    noArea: 'כללי',
    openTaskAria: 'פתיחת המשימה',
  },
  board: {
    rootAreaTitle: 'משימות כלליות',
    open: 'פתוחות',
    overdue: 'באיחור',
    empty: 'עוד אין מרחבים. אדמין יכול להוסיף תיקייה כדי להתחיל.',
    openAreaAria: 'פתיחת מרחב',
    back: 'חזרה',
  },
  form: {
    newTaskTitle: 'משימה חדשה',
    newFolderTitle: 'תיקייה חדשה',
    editTaskTitle: 'עריכת משימה',
    editFolderTitle: 'עריכת תיקייה',
    titleLabel: 'כותרת',
    location: 'מיקום',
    locationRoot: 'רמה ראשית',
    description: 'תיאור',
    descriptionPlaceholder: 'פרטים, הערות, קישורים…',
    owner: 'אחראי/ת',
    unassigned: 'לא משויך',
    skill: 'כישור נדרש',
    skillAnyone: 'כל עובד',
    scheduling: 'תזמון',
    once: 'חד-פעמי',
    repeats: 'חוזר',
    due: 'תאריך יעד',
    create: 'יצירה',
    save: 'שמירה',
    back: 'חזרה',
    delete: 'מחיקה',
  },
  view: {
    back: 'חזרה',
    edit: 'עריכה',
    markDone: 'סמן כבוצע',
    reopen: 'החזר לפתוח',
    noDescription: 'אין תיאור.',
    owner: 'אחראי/ת',
    unassigned: 'לא משויך',
    skill: 'כישור נדרש',
    due: 'תאריך יעד',
    statusOpen: 'פתוחה',
    statusDone: 'בוצעה',
    statusMissed: 'הוחמצה',
    subtasks: 'תת-משימות',
    addSub: 'הוספת תת-משימה',
    addSubDetailed: 'פתיחת משימה עם פרטים',
    completeAll: 'סמן הכול כבוצע',
    confirmTitle: 'יש תת-משימות פתוחות',
    stillOpen: 'פתוחות עדיין',
  },
  tasks: {
    addTask: 'משימה חדשה',
    addContainer: 'תיקייה חדשה',
    newTaskPlaceholder: 'מה צריך לעשות?',
    newContainerPlaceholder: 'שם התיקייה',
    add: 'הוספה',
    cancel: 'ביטול',
    emptyTitle: 'אין עדיין משימות',
    emptyBody: 'הוסיפו את הראשונה למטה.',
    detailTitle: 'פרטי משימה',
    titleLabel: 'כותרת',
    description: 'תיאור',
    descriptionPlaceholder: 'פרטים, הערות, קישורים…',
    assignee: 'אחראי/ת',
    unassigned: 'לא משויך',
    dueDate: 'תאריך יעד',
    noDue: 'ללא תאריך',
    save: 'שמירה',
    delete: 'מחיקה',
    addChildAria: 'הוספה לתיקייה',
    toggleDoneAria: 'סימון שהמשימה בוצעה',
    expandAria: 'פתיחה או סגירה של התיקייה',
    openTaskAria: 'פתיחת פרטי המשימה',
    claim: 'עלי',
    claimAria: 'לקחת על עצמי',
    claimNoSkill: 'אין לך את הכישור הנדרש',
    missed: 'הוחמצה',
    recurrence: {
      label: 'חזרה',
      none: 'בלי חזרה',
      freq: { daily: 'יומי', weekly: 'שבועי', monthly: 'חודשי' },
      everyLabel: 'כל',
      intervalLabel: 'כל כמה',
      pickDays: 'באילו ימים',
      onDays: 'ב',
      dayShort: ['א׳', 'ב׳', 'ג׳', 'ד׳', 'ה׳', 'ו׳', 'ש׳'],
      units: {
        day: { one: 'יום', two: 'יומיים', many: 'ימים' },
        week: { one: 'שבוע', two: 'שבועיים', many: 'שבועות' },
        month: { one: 'חודש', two: 'חודשיים', many: 'חודשים' },
      },
      until: 'עד',
      untilLabel: 'עד שעה',
      partOfSeries: 'מתוך משימה חוזרת',
    },
  },
  access: {
    loading: 'בודק מה קורה…',
    noAccessTitle: 'אופס, אין לך גישה לפה עדיין',
    noAccessBody: 'המרחב הזה פתוח רק לחברי הצוות. דברו עם מנהל כדי שיוסיפו אותך.',
    backToSite: 'חזרה לאתר',
  },
};
